### PR TITLE
Renamed references to Object -> Obj

### PR DESCRIPTION
**Pull request by trq**
This should bring `predaddy` back inline with `precore` once https://github.com/szjani/precore/pull/2 is merged.

### CODE REVIEW

**Comment by szjani** [comment]
Predaddy is also fixed, the changes can be found on a feature branch.
If there will be no issues then I'll merge the changes next week.

**Comment by trq** [comment]
HI Janos,

Thanks for these. I meant to reply earlier in the week but got sidetracked.

I had a quick look at the changes in precore, and it looks great! If you want to make some PRs for these changes I could go through and review if you like. Up to you really.

**Comment by szjani** [comment]
Version 4.0.0 contains all the fixes.

**Comment by trq** [comment]
Thanks!

**Pull request closed without merging**
