### PR TITLE
Let the event publisher take any message bus

### PR DESCRIPTION
**Pull request by redthor**
Could we get this? It means we can swap out the EventBus implementation.

### CODE REVIEW

**Comment by szjani** [comment]
Hi @redthor. Basically I don't see any reasons why it shouldn't be merged. I see that the 5.4 build failed, which is completely unrelated, so I'll fix that later.

**Comment by redthor** [comment]
Thanks @szjani !

**Comment by szjani** [comment]
Hi @redthor 
I've just released 3.0.3 that contains this PR and the build fix as well.
The build: https://travis-ci.org/szjani/predaddy/builds/139865035

**Comment by redthor** [comment]
Hi @szjani - great job, thanks! We can go back to the tagged release.

**Pull request merged**
